### ISSUE TITLE
[Suggestion] Prehaps make difficulty options ?

### ISSUE THREAD

**Issue by irpyc** [GunshipPenguin/open_flood#48]
Hej,
I was looking for game for my grandma on F-Droid, just found yours, it's amazing! 
Super game play, nice looking and clean app! 

I just found it at the limit of "too frustrating for further playing", fortunately I won the first time ever I played, but then it took me lot of attempts to win again... And still not winning often on a lot of tries
!

I would be really glad if you could make it more accessible for beginners, if you're so inclined (I don't really program, otherwise I would had made a fork myself) 
Prehaps difficulty options to get a couple of extra moves. 
What could also help is an option for a visual help, some borders to see exactly what is currently flooded 
[sketch-1547552124057](https://user-images.githubusercontent.com/22862277/51178721-c982e980-18c3-11e9-8f1f-2f9ff9653f9a.png)

Thanks,

**Comment by GunshipPenguin** [comment]
Hi there,

Thanks for the positive feedback :) I'm glad you're getting some use out of Open Flood.

Difficulty settings and a visual border are reasonable suggestions, however I'm not currently actively maintaining this repository due to a lack of time (I'm a full time student).

I can't make any promises, but I may put some more work into Open Flood in the future. If I do, I'll definitely keep your suggestions in mind.

Cheers,
Rhys
