### ISSUE TITLE
Brighter colors

### ISSUE THREAD

**Issue by twwd** [GunshipPenguin/open_flood#8]
It would be nice if the colors were brighter, i.e using the [material color palette](http://materialcolors.com/)

**Comment by GunshipPenguin** [comment]
04dea6ae247fc3678fc36f7d7e923378da25018d

As a small sidenote, the old colors were the colors of all the schools I've attended. I used them because I thought it would be a cool thing to tell people about, but they didn't really look that good together.

All the new colors have come from the material color palette.
